// website/react/app/components/Socials.tsx
import { Resume } from "../models/resume";

interface IProps {
  data: Resume;
}
export const Socials = ({ data }: IProps) => {
  return (
    <div className="space-x-4">
      {data.social.mail && (
        <a href={"mailto:" + data.social.mail} className="hover:text-accent">
          <i className="fa-regular fa-envelope fa-xl"></i>
        </a>
      )}
      {data.social.github && (
        <a
          href={data.social.github}
          className="hover:text-accent"
          target="_blank"
        >
          <i className="fa-brands fa-github fa-xl"></i>
        </a>
      )}
      {data.social.linkedin && (
        <a
          href={data.social.linkedin}
          className="hover:text-accent"
          target="_blank"
        >
          <i className="fa-brands fa-linkedin-in fa-xl"></i>
        </a>
      )}
    </div>
  );
};

// website/angular/src/app/components/socials.component.ts
import { Component, Input } from '@angular/core';
import { Resume } from '../models/resume';

@Component({
  standalone: true,
  selector: 'socials',
  imports: [],
  template: `
    <div class="space-x-4">
      @if(data && data.social.mail){
      <a [href]="'mailto:' + data.social.mail" class="hover:text-accent">
        <i class="fa-regular fa-envelope fa-xl"></i>
      </a>
      } @if(data && data.social.github){
      <a [href]="data.social.github" class="hover:text-accent" target="_blank">
        <i class="fa-brands fa-github fa-xl"></i>
      </a>
      } @if(data && data.social.linkedin){
      <a
        [href]="data.social.linkedin"
        class="hover:text-accent"
        target="_blank"
      >
        <i class="fa-brands fa-linkedin-in fa-xl"></i>
      </a>
      }
    </div>
  `,
})
export class Socials {
  @Input({ required: true }) data: Resume | undefined = undefined;
}
