// website/react/app/components/General/PhotoCard.tsx
import { CardItem } from "./CardItem";

interface IProps {
  preview: React.ReactNode;
  title: React.ReactNode;
  body: React.ReactNode;
  href: string;
}
export const PhotoCard = ({ preview, title, body, href }: IProps) => {
  return (
    <CardItem
      href={href}
      title={title}
      preview={
        <div className="flex place-content-center">
          <div className="max-w-32">{preview}</div>
        </div>
      }
      body={body}
    />
  );
};

// website/vue/src/components/General/PhotoCard.vue
<script setup lang="ts">
import { ref } from 'vue'
import Card from './Card.vue'
import CardItem from './CardItem.vue'
import TagList from '../TagList.vue'
defineProps<{
  href?: string
}>()
</script>

<template>
  <CardItem :href="href">
    <template #title> <slot name="title" /></template>
    <template #preview>
      <div class="flex place-content-center">
        <div class="max-w-32">
          <slot name="preview" />
        </div>
      </div>
    </template>
    <template #body>
      <slot name="body" />
    </template>
  </CardItem>
</template>

<style lang=""></style>
