// website/vue/src/components/General/DateCard.vue
<script setup lang="ts">
import { ref } from 'vue'
import Card from './Card.vue'
import CardItem from './CardItem.vue'
import TagList from '../TagList.vue'
defineProps<{
  href?: string
}>()
</script>

<template>
  <CardItem :href="href">
    <template #title> <slot name="title" /></template>
    <template #preview>
      <p class="text-xs text-text opacity-50 uppercase font-semibold">
        <slot name="preview" />
      </p>
    </template>
    <template #body>
      <slot name="body" />
    </template>
  </CardItem>
</template>

<style lang=""></style>

// website/react/app/components/General/DateCard.tsx
import { CardItem } from "./CardItem";

interface IProps {
  preview: React.ReactNode;
  title: React.ReactNode;
  body: React.ReactNode;
  href: string;
}
export const DateCard = ({ preview, title, body, href }: IProps) => {
  return (
    <CardItem
      href={href}
      title={title}
      preview={
        <p className="text-xs text-text opacity-50 uppercase font-semibold">
          {preview}
        </p>
      }
      body={body}
    />
  );
};
