// website/vue/src/pages/Projects.vue
<script setup lang="ts">
import { BaseSection, ProjectCard } from '@/components/index.js'
import type { Project } from '../models/resume.ts'

defineProps<{
  data: Project[]
}>()
</script>

<template>
  <BaseSection title="Projects">
    <ProjectCard v-for="project in data" :data="project" />
  </BaseSection>
</template>

// website/angular/src/app/pages/projects.component.ts
import { Component, Input } from '@angular/core';
import { ProjectCard } from '../components/project-card.component';
import { Project } from '../models/resume';
import { BaseSection } from './../components/base-section.component';

@Component({
  standalone: true,
  selector: 'projects',
  imports: [BaseSection, ProjectCard],
  template: `
    <base-section title="Projects">
      @for(project of data; track $index){
      <div [class]="$index > 0 ? 'pt-1' : ''">
        <project-card [data]="project" />
      </div>
      }
    </base-section>
  `,
})
export class Projects {
  @Input({ required: true }) data!: Project[];
}
