// website/react/app/pages/Experience.tsx
import { BaseSection } from "../components/BaseSection";
import { ExperienceCard } from "../components/ExperienceCard";
import { Experience as ExperienceItem } from "../models/resume";

interface IProps {
  data: ExperienceItem[];
}
export const Experience = ({ data }: IProps) => {
  return (
    <BaseSection title="Experience">
      {data.map((experience, i) => (
        <ExperienceCard key={i} data={experience} />
      ))}
    </BaseSection>
  );
};

// website/vue/src/pages/Experience.vue
<script setup lang="ts">
import { ExperienceCard, BaseSection } from '@/components/index.js'
import type { Experience } from '../models/resume.ts'

defineProps<{
  data: Experience[]
}>()
</script>

<template>
  <BaseSection title="Experience">
    <ExperienceCard v-for="experience in data" :data="experience" />
  </BaseSection>
</template>
