// website/react/app/pages/Projects.tsx
import { BaseSection } from "../components/BaseSection";
import { ProjectCard } from "../components/ProjectCard";
import { Project } from "../models/resume";

interface IProps {
  data: Project[];
}
export const Projects = ({ data }: IProps) => {
  return (
    <BaseSection title="Projects">
      {data.map((project, i) => (
        <ProjectCard key={i} data={project} />
      ))}
    </BaseSection>
  );
};

// website/vue/src/pages/Projects.vue
<script setup lang="ts">
import { BaseSection, ProjectCard } from '@/components/index.js'
import type { Project } from '../models/resume.ts'

defineProps<{
  data: Project[]
}>()
</script>

<template>
  <BaseSection title="Projects">
    <ProjectCard v-for="project in data" :data="project" />
  </BaseSection>
</template>
