// website/angular/src/app/components/base-section.component.ts
import { Component, Input } from '@angular/core';
import { SectionHeader } from './general/section-header.component';

@Component({
  standalone: true,
  selector: 'base-section',
  imports: [SectionHeader],
  template: `
    <div class="container flex-row space-y-1">
      <section-header>{{ title }}</section-header>
      <div class="space-y-2"><ng-content /></div>
    </div>
  `,
})
export class BaseSection {
  @Input({ required: true }) title = '';
}

// website/react/app/components/BaseSection.tsx
import { SectionHeader } from "./General/SectionHeader";

interface IProps {
  children: React.ReactNode;
  title: string;
}
export const BaseSection = ({ children, title }: IProps) => {
  return (
    <div className="container flex-row space-y-1">
      <SectionHeader>{title}</SectionHeader>
      <div className="space-y-2">{children}</div>
    </div>
  );
};
