// website/vue/src/components/BaseSection.vue
<script setup lang="ts">
import { SectionHeader } from './General'

const props = defineProps<{
  title: string
}>()
</script>

<template>
  <div class="container flex-row space-y-1">
    <SectionHeader>{{ title }}</SectionHeader>
    <div class="space-y-2">
      <slot></slot>
    </div>
  </div>
</template>

// website/react/app/components/BaseSection.tsx
import { SectionHeader } from "./General/SectionHeader";

interface IProps {
  children: React.ReactNode;
  title: string;
}
export const BaseSection = ({ children, title }: IProps) => {
  return (
    <div className="container flex-row space-y-1">
      <SectionHeader>{title}</SectionHeader>
      <div className="space-y-2">{children}</div>
    </div>
  );
};
