// website/vue/src/components/EducationCard.vue
<script setup lang="ts">
import type { Education } from '@/models/resume'
import DateCard from './General/DateCard.vue'
import TagList from './TagList.vue'
import { CardListDetails } from './General'

defineProps<{
  data: Education
}>()
</script>

<template>
  <DateCard :href="data.link">
    <template #title>{{ data.title + ' · ' + data.school }}</template>
    <template #preview>
      {{ data.duration }}
    </template>
    <template #body>
      <CardListDetails :data="data.description" />
    </template>
  </DateCard>
</template>

// website/react/app/components/EducationCard.tsx
import { Education } from "../models/resume";
import { CardListDetails } from "./General/CardListDetails";
import { DateCard } from "./General/DateCard";

interface IProps {
  data: Education;
}
export const EducationCard = ({ data }: IProps) => {
  return (
    <DateCard
      href={data.link}
      preview={data.duration}
      body={<CardListDetails data={data.description} />}
      title={data.title + " · " + data.school}
    />
  );
};
