// website/vue/src/components/ExperienceCard.vue
<script setup lang="ts">
import type { Experience } from '@/models/resume'
import DateCard from './General/DateCard.vue'
import TagList from './TagList.vue'

defineProps<{
  data: Experience
}>()
</script>

<template>
  <DateCard :href="data.link">
    <template #title>{{ data.title + ' · ' + data.company }}</template>
    <template #preview>
      {{ data.duration }}
    </template>
    <template #body>
      <ul class="list-disc pl-3.5">
        <li v-for="desc in data.description">
          {{ desc }}
        </li>
      </ul>
      <TagList :tags="data.tags" />
    </template>
  </DateCard>
</template>

// website/react/app/components/ExperienceCard.tsx
import { Experience } from "../models/resume";
import { CardListDetails } from "./General/CardListDetails";
import { DateCard } from "./General/DateCard";
import { TagList } from "./TagList";

interface IProps {
  data: Experience;
}
export const ExperienceCard = ({ data }: IProps) => {
  return (
    <DateCard
      href={data.link}
      title={data.title + " · " + data.company}
      preview={data.duration}
      body={
        <>
          <CardListDetails data={data.description} />
          <TagList tags={data.tags} />
        </>
      }
    />
  );
};
