// website/angular/src/app/components/project-card.component.ts
import { Component, Input } from '@angular/core';
import { Project } from '../models/resume';
import { FigmaLink } from './figma-link.component';
import { CardTextDetails } from './general/card-text-details.component';
import { PhotoCard } from './general/photo-card.component';
import { GithubLink } from './github-link.component';
import { TagList } from './tag-list.component';

@Component({
  standalone: true,
  selector: 'project-card',
  imports: [PhotoCard, CardTextDetails, TagList, FigmaLink, GithubLink],
  template: `
    <photo-card [href]="data.link" [title]="data.title">
      <div ngProjectAs="preview" class="flex place-content-center">
        <div class="max-w-32 mb-3">
          <img
            [src]="imageUrl"
            class="rounded-md border-2 border-accent-darker"
          />
        </div>
      </div>
      <card-text-details [data]="data.description" />
      <div class="py-1">
        <tag-list [tags]="data.tags" />
      </div>
      <div class="space-x-2.5">
        @if(data.figma){
        <figma-link [href]="data.figma" />
        } @if(data.github){
        <github-link [href]="data.github" />
        }
      </div>
    </photo-card>
  `,
})
export class ProjectCard {
  @Input({ required: true }) data!: Project;
  baseUrl = '';
  imageUrl = '';

  ngOnInit() {
    this.baseUrl = window.location.origin;
    this.imageUrl = new URL(
      this.baseUrl + '/' + this.data.photo,
      import.meta.url
    ).href;
    console.log(this.baseUrl);
  }
}

// website/react/app/components/ProjectCard.tsx
"use client";
import { useEffect, useState } from "react";
import { Project } from "../models/resume";
import { FigmaLink } from "./FigmaLink";
import { CardTextDetails } from "./General/CardTextDetails";
import { PhotoCard } from "./General/PhotoCard";
import { GithubLink } from "./GithubLink";
import { TagList } from "./TagList";

interface IProps {
  data: Project;
}
export const ProjectCard = ({ data }: IProps) => {
  const [imageUrl, setImageUrl] = useState("");
  useEffect(() => {
    const baseUrl = window.location.origin;
    const imageUrl = new URL(baseUrl + "/" + data.photo, import.meta.url).href;
    setImageUrl(imageUrl);
  });
  return (
    <PhotoCard
      href={data.link}
      title={data.title}
      preview={
        <div className="flex place-content-center">
          <div className="max-w-32 mb-3">
            <img
              src={imageUrl}
              className="rounded-md border-2 border-accent-darker"
            />
          </div>
        </div>
      }
      body={
        <>
          <CardTextDetails data={data.description} />
          <TagList tags={data.tags} />
          <div className="space-x-2.5">
            {data.figma && <FigmaLink href={data.figma} />}
            {data.github && <GithubLink href={data.github} />}
          </div>
        </>
      }
    ></PhotoCard>
  );
};
