// website/angular/src/app/components/tag-list.component.ts
import { Component, Input } from '@angular/core';
import { Tag } from './general/tag.component';

@Component({
  standalone: true,
  selector: 'tag-list',
  imports: [Tag],
  template: `
    @if(tags){
    <div class="inline-flex flex-wrap gap-1">
      @for(tag of tags; track tag){
      <tag>{{ tag }}</tag>
      }
    </div>
    }
  `,
})
export class TagList {
  @Input({ required: true }) tags: string[] | undefined = undefined;
}

// website/react/app/components/TagList.tsx
import { Tag } from "./General/Tag";

interface IProps {
  tags: string[] | undefined;
}
export const TagList = ({ tags }: IProps) => {
  return tags ? (
    <div className="inline-flex flex-wrap gap-1">
      {tags.map((tag, i) => (
        <Tag key={i}>{tag}</Tag>
      ))}
    </div>
  ) : null;
};
