// website/react/app/components/BlogPostCard.tsx
"use client";
import { useEffect, useState } from "react";
import { BlogPost } from "../models/resume";
import { CardTextDetails } from "./General/CardTextDetails";
import { PhotoCard } from "./General/PhotoCard";
import { TagList } from "./TagList";

interface IProps {
  data: BlogPost;
}
export const BlogPostCard = ({ data }: IProps) => {
  const [imageUrl, setImageUrl] = useState("");
  useEffect(() => {
    const baseUrl = window.location.origin;
    const imageUrl = new URL(baseUrl + "/" + data.photo, import.meta.url).href;
    setImageUrl(imageUrl);
  });
  return (
    <PhotoCard
      href={data.link}
      preview={
        <div className="flex place-content-center">
          <div className="max-w-32 mb-3">
            <img
              src={imageUrl}
              className="rounded-md border-2 border-accent-darker"
            />
          </div>
        </div>
      }
      body={
        <>
          <CardTextDetails data={data.description} />
          <TagList tags={data.tags} />
        </>
      }
      title={data.title}
    ></PhotoCard>
  );
};

// website/vue/src/components/BlogPostCard.vue
<script setup lang="ts">
import type { BlogPost } from '@/models/resume'
import { CardTextDetails, PhotoCard } from './General'
import TagList from './TagList.vue'
const props = defineProps<{
  data: BlogPost
}>()

const baseUrl = window.location.origin
const imageUrl = new URL(baseUrl + '/' + props.data.photo, import.meta.url).href
</script>
<template>
  <PhotoCard :href="data.link">
    <template #title>{{ data.title }}</template>
    <template #preview>
      <div class="flex place-content-center">
        <div class="max-w-32 mb-3">
          <img :src="imageUrl" class="rounded-md border-2 border-accent-darker" />
        </div>
      </div>
    </template>
    <template #body>
      <CardTextDetails :data="data.description" />
      <TagList :tags="data.tags" />
    </template>
  </PhotoCard>
</template>
