// website/react/app/components/ProjectCard.tsx
"use client";
import { useEffect, useState } from "react";
import { Project } from "../models/resume";
import { FigmaLink } from "./FigmaLink";
import { CardTextDetails } from "./General/CardTextDetails";
import { PhotoCard } from "./General/PhotoCard";
import { GithubLink } from "./GithubLink";
import { TagList } from "./TagList";

interface IProps {
  data: Project;
}
export const ProjectCard = ({ data }: IProps) => {
  const [imageUrl, setImageUrl] = useState("");
  useEffect(() => {
    const baseUrl = window.location.origin;
    const imageUrl = new URL(baseUrl + "/" + data.photo, import.meta.url).href;
    setImageUrl(imageUrl);
  });
  return (
    <PhotoCard
      href={data.link}
      title={data.title}
      preview={
        <div className="flex place-content-center">
          <div className="max-w-32 mb-3">
            <img
              src={imageUrl}
              className="rounded-md border-2 border-accent-darker"
            />
          </div>
        </div>
      }
      body={
        <>
          <CardTextDetails data={data.description} />
          <TagList tags={data.tags} />
          <div className="space-x-2.5">
            {data.figma && <FigmaLink href={data.figma} />}
            {data.github && <GithubLink href={data.github} />}
          </div>
        </>
      }
    ></PhotoCard>
  );
};

// website/vue/src/components/ProjectCard.vue
<script setup lang="ts">
import type { Project } from '@/models/resume'
import DateCard from './General/DateCard.vue'
import TagList from './TagList.vue'
import PhotoCard from './General/PhotoCard.vue'
import FigmaLink from './FigmaLink.vue'
import GithubLink from './GithubLink.vue'
import { ref } from 'vue'

const props = defineProps<{
  data: Project
}>()

const baseUrl = window.location.origin
const imageUrl = new URL(baseUrl + '/' + props.data.photo, import.meta.url).href
// const imgPath = require('@/assets/' + props.data.photo)
</script>
<template>
  <PhotoCard :href="data.link">
    <template #title>{{ data.title }}</template>
    <template #preview>
      <div class="flex place-content-center">
        <div class="max-w-32 mb-3">
          <img :src="imageUrl" class="rounded-md border-2 border-accent-darker" />
        </div>
      </div>
    </template>
    <template #body>
      <p class="opacity-80" v-for="desc in data.description">
        {{ desc }}
      </p>
      <TagList :tags="data.tags" />
      <div class="space-x-2.5">
        <FigmaLink v-if="data.figma" :href="data.figma" />
        <GithubLink v-if="data.github" :href="data.github" />
      </div>
    </template>
  </PhotoCard>
</template>
