// website/vue/src/pages/BlogPosts.vue
<script setup lang="ts">
import { BlogPostCard, BaseSection } from '@/components/index.js'
import type { BlogPost } from '@/models/resume'

defineProps<{
  data: BlogPost[]
}>()
</script>

<template>
  <BaseSection title="Blog">
    <BlogPostCard v-for="post in data" :data="post" />
  </BaseSection>
</template>

// website/react/app/pages/BlogPosts.tsx
import { BaseSection } from "../components/BaseSection";
import { BlogPostCard } from "../components/BlogPostCard";
import { BlogPost } from "../models/resume";

interface IProps {
  data: BlogPost[];
}
export const BlogPosts = ({ data }: IProps) => {
  return (
    <BaseSection title="Blog">
      {data.map((post, i) => (
        <BlogPostCard key={i} data={post} />
      ))}
    </BaseSection>
  );
};
