// website/vue/src/pages/Education.vue
<script setup lang="ts">
import { EducationCard, BaseSection } from '@/components/index.js'
import type { Education, Project } from '../models/resume.ts'

defineProps<{
  data: Education[]
}>()
</script>

<template>
  <BaseSection title="Education">
    <EducationCard v-for="education in data" :data="education" />
  </BaseSection>
</template>

// website/react/app/pages/Education.tsx
import { BaseSection } from "../components/BaseSection";
import { EducationCard } from "../components/EducationCard";
import { Education as EducationItem } from "../models/resume";

interface IProps {
  data: EducationItem[];
}
export const Education = ({ data }: IProps) => {
  return (
    <BaseSection title="Education">
      {data.map((education, i) => (
        <EducationCard key={i} data={education} />
      ))}
    </BaseSection>
  );
};
